"""Added rights and roles

Revision ID: 1b5bc7d316ec
Revises: 147753115be3
Create Date: 2025-01-19 18:17:56.852076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b5bc7d316ec"
down_revision: Union[str, None] = "147753115be3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Right",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("owner_only", sa.Boolean(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("create", sa.Boolean(), nullable=False),
        sa.Column("update", sa.Boolean(), nullable=False),
        sa.Column("delete", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model", "owner_only", "read", "create", "update", "delete"),
    )
    op.create_table(
        "Role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "roles_rights_relation",
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("right_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["right_id"],
            ["Right.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["Role.id"],
        ),
    )
    op.add_column("User", sa.Column("role", sa.String(length=50), nullable=False))
    op.create_foreign_key(None, "User", "Role", ["role"], ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "User", type_="foreignkey")
    op.drop_column("User", "role")
    op.drop_table("roles_rights_relation")
    op.drop_table("Role")
    op.drop_table("Right")
    # ### end Alembic commands ###
