"""Changed role_name in user

Revision ID: 1d7cba497094
Revises: 1b5bc7d316ec
Create Date: 2025-01-20 23:27:46.040894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1d7cba497094"
down_revision: Union[str, None] = "1b5bc7d316ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("User", sa.Column("role_name", sa.String(length=50), nullable=False))
    op.drop_constraint("User_role_fkey", "User", type_="foreignkey")
    op.create_foreign_key(None, "User", "Role", ["role_name"], ["name"])
    op.drop_column("User", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "User", sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "User", type_="foreignkey")
    op.create_foreign_key("User_role_fkey", "User", "Role", ["role"], ["name"])
    op.drop_column("User", "role_name")
    # ### end Alembic commands ###
